spring.application.name=customer-ms
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Service URLs
account.ms.url=${ACCOUNT_MS_URL}

# API Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.alessandragodoy.customerms.controller,com.alessandragodoy.customerms.api
springdoc.paths-to-match=/api/v1/customers/**,/api/v1/internal/customers/**
springdoc.swagger-ui.operationsSorter=null
server.forward-headers-strategy=framework

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
