spring.application.name=customer-ms
server.port=8085

# Database
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Service URLs
account.ms.url=${ACCOUNT_MS_URL}

# API Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.forward-headers-strategy=framework

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
